### ISSUE TITLE
Can new calendar : France, be added ?

### ISSUE THREAD

**Issue by NJeanray** [eddelbuettel/rquantlib#134]
Hello,

Would it be possible to add French calendar from QuantLib ?
It has been added about 1 month ago :+1: 

France::SettlementImpl
France::ExchangeImpl

Regards,
Nathalie

**Comment by eddelbuettel** [comment]
It should just appear when your version (of the R package) is rebuilt using the new QuantLib sources. Otherwise you may need to wait for the QuantLib release and a build.

What platform are you on?  WIndows?

**Comment by NJeanray** [comment]
Yes, I'm on Windows 7, x64 :+1: 

R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252    

Here is my version of RQuantLib : 0.4.8

Could you please give me the commands to proceed ?

Thanks in advance !

**Comment by eddelbuettel** [comment]
As I tried to explain,
 - code that is in QuantLib itself
 - reaches you via a binary build of QuantLib
 - so if you want it in RQuantLib
 - the binary build of QuantLib needs to be updated
That is ... somewhat involved.  See old issue tickets here eg for the macOS users but also windows.

Otherwise you will have to wait for the next releases of QuantLib and the RQuantLib for other people to do this for you.
