### ISSUE TITLE
Time to maturity being approximated by 360 days a year instead of 365

### ISSUE THREAD

**Issue by abysmon** [eddelbuettel/rquantlib#15]
The days calculation is now being `int(maturity*360 + 0.5)` which for some time periods make a difference of 1 day when being used in European option implied volatility calculation. Hence subsequently all the option greeks also diverge.

**Comment by eddelbuettel** [comment]
I am sorry but 
+ What file? 
+ What function? 
+ Diverge relative to _what_?

**Comment by abysmon** [comment]
Sorry for the incomplete report. I was talking about this line https://github.com/eddelbuettel/rquantlib/blob/master/src/implieds.cpp#L39, and a similar line in the code later on. Why the maturity is being converted as `int(maturity*360 + 0.5)` instead of `int(maturity*365)` ? I'm sure this will give better date retrieval than the previous one.

**Comment by eddelbuettel** [comment]
Both are approximations, and both suffer from non-smooth rounding cutoffs. Using 12 months of 30 days is frequently used, sometimes 365 is preferred, others even use 365.25.  That's why fixed income is full of settlement conventions.

This is meant to be an example toolkit provided as source: if you think you really need it differently, just build it locally.  But this is not a case of one being demonstrably right or wrong so I do not think I was to change this:  what we really want much better date arithmetic in QuantLib itself.

**Comment by eddelbuettel** [comment]
You may like what is now in the master branch -- intra-day time for options too.  Requires QuantLin 1.7 configured with `--enable-intraday`.
