### ISSUE TITLE
0.4.2 in cron

### ISSUE THREAD

**Issue by kismsu** [eddelbuettel/rquantlib#29]
Hi, I've just notice that new version doesn't want to load the package `library(RQuantLib)`. Looks like it fails when tries to check QuantLib config.

**Comment by eddelbuettel** [comment]
You have to provide a bit more detail if you want me to do anything but closing this. The keyword is 'minimally reproducible example'.

Here is a counter-example:

```bash
edd@max:~$ r -lRQuantLib -e'print(getQuantLibVersion())'
[1] "1.7"
edd@max:~$ r  -e'library(RQuantLib); print(getQuantLibVersion())'
[1] "1.7"
edd@max:~$ 
```

**Comment by kismsu** [comment]
Yes, finally got it. If you put into cron the following script

```r
tryCatch({
    library(RQuantLib)
}, error = function(e) {
    print(e)
    cat(e)
})
```

The output is the following
```
<simpleError: package or namespace load failed for ‘RQuantLib’>
```

**Comment by kismsu** [comment]
```
r -lRQuantLib -e'print(getQuantLibVersion())'
1.6.1
```

**Comment by eddelbuettel** [comment]
I would start by reinstalling QuantLib to become current (you are two releases behind).  With that, reinstall RQuantLib.  I have binaries for Ubuntu (if that is what you use) [in my PPA](https://launchpad.net/~edd/+archive/ubuntu/misc/+packages); Debian has them in unstable accessible from testing.  For all other distros you are on your own.

There is no actual bug here (as best as I can tell) so I am closing this.  If you have something reproducible besides a borked local installation, feel free to open a new report.
